/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Dialog.ModalityType;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.stage.Stage;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import model.message;
import project.messageBox;

/**
 *
 * @author Kale
 */
public class main extends javax.swing.JFrame {

    int x,y,maxi=0,usr=1,pwd=1,xx,yy;
    String txtu="",txtp="";
    
    public main() {
        
        setUndecorated(true);
        setBackground(new Color(0, 255, 0, 0));
        setLocationRelativeTo(null);
        
        initComponents();
        
        jPanel1.setBackground(new Color(0, 255, 0, 0));
        
        btnlogin.setOpaque(false);
        btnlogin.setContentAreaFilled(false);
        btnlogin.setBorderPainted(false);
        txtpwd.setEchoChar('•');
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        show = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        logbtn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jPanel1.setMinimumSize(new java.awt.Dimension(882, 662));
        jPanel1.setLayout(null);

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(660, 320, 80, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Password");
        jLabel10.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 300, 60, 15);

        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini.png"))); // NOI18N
        mini.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel1.add(mini);
        mini.setBounds(790, 10, 20, 20);

        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/max.png"))); // NOI18N
        max.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });
        jPanel1.add(max);
        max.setBounds(820, 10, 20, 20);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        close.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(850, 10, 20, 20);

        jLabel2.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel2KeyTyped(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 41);

        btnlogin.setBackground(new java.awt.Color(153, 153, 153));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        btnlogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnloginMouseMoved(evt);
            }
        });
        btnlogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnloginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnloginFocusLost(evt);
            }
        });
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnloginMouseExited(evt);
            }
        });
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(270, 440, 360, 40);

        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnlogin.png"))); // NOI18N
        logbtn.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        logbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logbtnMouseClicked(evt);
            }
        });
        jPanel1.add(logbtn);
        logbtn.setBounds(270, 440, 360, 40);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 180, 25, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("System");
        jLabel6.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel6);
        jLabel6.setBounds(421, 10, 50, 20);

        txtuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuser.setText("Username");
        txtuser.setToolTipText("Username");
        txtuser.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });
        jPanel1.add(txtuser);
        txtuser.setBounds(270, 180, 360, 40);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lock.png"))); // NOI18N
        jLabel8.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 320, 25, 40);

        txtpwd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpwd.setText("Password");
        txtpwd.setToolTipText("Password");
        txtpwd.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        txtpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpwdFocusLost(evt);
            }
        });
        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });
        txtpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpwdKeyTyped(evt);
            }
        });
        jPanel1.add(txtpwd);
        txtpwd.setBounds(270, 320, 360, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Username");
        jLabel11.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 160, 60, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/frame.png"))); // NOI18N
        jLabel1.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 882, 662);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 670);

        setBounds(0, 0, 900, 702);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        
        xx = evt.getXOnScreen();
        yy = evt.getYOnScreen();
        
        this.setLocation(xx-x, yy-y);
        
        if(maxi%2==0){
            setExtendedState(JFrame.NORMAL);
        }
        
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        
        x = evt.getX();
        y = evt.getY();
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        
        maxi++;
        
        if(maxi%2==0){
            setExtendedState(JFrame.NORMAL);
        }
        else if(maxi%2==1){
            jPanel1.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
            //jLabel1.setSize();
            setExtendedState(this.getExtendedState()|main.MAXIMIZED_BOTH);
            
        }
        
        
    }//GEN-LAST:event_maxMouseClicked

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        btnloginActionPerformed(evt);
    }//GEN-LAST:event_txtuserActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyTyped
        
    }//GEN-LAST:event_jLabel2KeyTyped

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        txtu=txtuser.getText();
        
        txtuser.setOpaque(false);
        
    }//GEN-LAST:event_txtuserKeyTyped

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
        txtuser.setOpaque(false);
        
    }//GEN-LAST:event_txtuserMouseClicked

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
        txtuser.setOpaque(false);
        
        if(usr==1){
            txtuser.setText("");
            usr++;
        }else if(txtu=="Username"){
            txtuser.setText("");
            txtu="";
        }
        
    }//GEN-LAST:event_txtuserFocusGained

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
        
        if(txtuser.getText().equals("")){
            txtuser.setText("Username");
            txtu="Username";
        }
        
    }//GEN-LAST:event_txtuserFocusLost

    private void txtpwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwdFocusGained
        txtpwd.setOpaque(false);
        
        if(pwd==1){
            txtpwd.setText("");
            pwd++;
        }else if(txtp=="Password"){
            txtpwd.setText("");
            txtp="";
        }
    }//GEN-LAST:event_txtpwdFocusGained

    private void txtpwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwdFocusLost
        
        if(txtpwd.getText().equals("")){
            txtpwd.setText("Password");
            txtp="Password";
        }
        
    }//GEN-LAST:event_txtpwdFocusLost

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        
        if(txtuser.getText().equals("")&&txtpwd.getText().equals("")){
            
            JFrame option = new messageBox("Filed Username & Password");
            option.setVisible(true);
            option.setLocation(xx-x+291,yy-y+256);
            
        }else if(txtu=="Username"&&txtp=="Password"){
            
            JFrame option = new messageBox("Filed Username & Password");
            option.setVisible(true);
            option.setLocation(xx-x+291,yy-y+256);
            
        }else{
            
            try{
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                Connection conn;
                ResultSet rs;

                conn = DriverManager.getConnection("jdbc:derby:C:\\Users\\Pavan\\AppData\\Roaming\\NetBeans\\Derby\\supermarket", "super", "udara123Kk");
                //System.out.println("connected");

                Statement stm=conn.createStatement();
                //System.out.println("statement created");

                String db;
                db = "select * from SUPER.users where USERNAME='"+txtuser.getText()+"' and PASSWORD='"+txtpwd.getText()+"'";

                rs = stm.executeQuery(db);
                //System.out.println("retrieving ...");

                if(rs.next()){

                    setVisible(false);
                    JOptionPane.showMessageDialog(null, "sucsessful");
                    System.out.println("sucsessful");

                }else{

                    JFrame option = new messageBox("Username or Password Incorrect");
                    option.setVisible(true);
                    option.setLocation(xx-x+290, yy-y+255);
                    
                }

            }
            catch(ClassNotFoundException | SQLException e){

            }
        }
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtpwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpwdKeyTyped
        txtp=txtpwd.getText();
    }//GEN-LAST:event_txtpwdKeyTyped

    private void logbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseClicked
        
    }//GEN-LAST:event_logbtnMouseClicked

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
       
    }//GEN-LAST:event_btnloginMouseClicked

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        btnloginActionPerformed(evt);
    }//GEN-LAST:event_txtpwdActionPerformed

    private void btnloginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnloginFocusGained
        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnloginf.png")));
    }//GEN-LAST:event_btnloginFocusGained

    private void btnloginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseMoved
        
    }//GEN-LAST:event_btnloginMouseMoved

    private void btnloginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnloginFocusLost
        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnlogin.png")));
    }//GEN-LAST:event_btnloginFocusLost

    private void btnloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseEntered
        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnloginf.png")));
    }//GEN-LAST:event_btnloginMouseEntered

    private void btnloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseExited
        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnlogin.png")));
    }//GEN-LAST:event_btnloginMouseExited

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maxc.png")));
    }//GEN-LAST:event_maxMouseEntered

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered
        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minic.png")));
    }//GEN-LAST:event_miniMouseEntered

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/closec.png")));
    }//GEN-LAST:event_closeMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited
        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini.png")));
    }//GEN-LAST:event_miniMouseExited

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/max.png")));
    }//GEN-LAST:event_maxMouseExited

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png")));
    }//GEN-LAST:event_closeMouseExited

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        
        if(show.isSelected()){
            txtpwd.setEchoChar((char)0);
        }else{
            txtpwd.setEchoChar('•');
        }
        
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logbtn;
    private javax.swing.JLabel max;
    private javax.swing.JLabel mini;
    private javax.swing.JCheckBox show;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
